### ISSUE TITLE
'Enter' new line broken

### ISSUE THREAD

**Issue by Arrogance** [billymoon/Stylus#43]
Related #12 

With the last revision, the enter key doesn't work with stylus syntax enabled. Reverted to old version of " Default.sublime-keymap" and it works.

**Comment by matteocontrini** [comment]
I'm having the same issue, reinstalled as you mentioned but still the same.

**Comment by grassator** [comment]
@matteocontrini could you please give me exact Sublime version and the sequence of events that causes the failure?

**Comment by matteocontrini** [comment]
Build 3083.
But it's strange because when writing in a .styl file, everything works fine. But in my case I need the Stylus syntax inside a .vue file, which is highlighted by [vue-syntax-highlight](https://github.com/vuejs/vue-syntax-highlight), which uses Sublime Stylus (this repo) for highlighting the syntax. And with this configuration I'm having issues. Specifically, pressing enter at the end of the line doesn't do anything, and this happens always. Enter works when the cursor is at the beginning of the line.

**Comment by grassator** [comment]
Ok, now this makes a bit more sense and is probably somehow connected to that language nesting and scopes, although I'm not sure how exactly. Please create a separate issue for this and I will take a look when I have some time, hopefully this week.
