### ISSUE TITLE
Integrating Stylus Build System with Nib in Sublime Text

### ISSUE THREAD

**Issue by jtstrohl** [billymoon/Stylus#47]
Hi.  I am trying to use Nib with Stylus in Sublime Text, so I have added **@import 'nib'** to my _.styl_ file.

I can compile with Nib from the command line, using the **-u** argument, like so:

```
> stylus -u Nib MyStyle.styl
```

But I'd like to be able to build from within Sublime Text using the Build System.  When I do, it fails with error

```
failed to locate @import file nib.styl
```

I imagine this is because it's not specifying the **-u** argument.

How can I integrate the Stylus Build System with Nib in Sublime Text?

Thanks in advance.

**Comment by frog42** [comment]
I'm using NVM, so the default paths you set it to check for nib didn't work.  I also use Jeet, so it'd be nice if there were a user setting where we could specify a search path for multiple items to be used during compiling and their respective paths.

It would actually work fine if you just had it default to search the same /bin/ designated in the user preference settings, since these things all tend to be in the same location.

Thanks for your work on this, before using Nib and Jeet, I had zero problems and really love compiling straight from Sublime Text.

**Comment by billymoon** [comment]
@frog42 looks like you already have all the details of the problem clearly defined - any chance you could implement the fix to and send a pull request?

Glad you like the package.

**Comment by frog42** [comment]
@billymoon I appreciate your confidence in my abilities, but I'm afraid I'm still quite a noob in git (and many other things).  I have a temporary workaround just watching files, but if I manage to find some free time I might see if I can figure it out.
