### ISSUE TITLE
Nib

### ISSUE THREAD

**Issue by sinystr** [billymoon/Stylus#56]
I have an issue, I have node.js and nib installed, when I compile from the console everything works, but when I try to comple from sublime:
![default](https://cloud.githubusercontent.com/assets/5150853/6997511/63761fa6-dbc6-11e4-8d0b-b1d0879e53a3.png)
I'm trying to fix this issue for hours and nothing. Please, help! 
Regards :)

**Comment by grassator** [comment]
Unfortunately I can't help much with this. This not reproducible on mac, and have neither Windows nor experience using node there, sorry.

**Comment by billymoon** [comment]
@sinystr this appears to be an issue with stylus itself, and not the sublime text plugin. I also don't have windows machine to reproduce the error, but I might guess it is because you don't have [`nib`](https://github.com/tj/nib) installed...

    npm install nib

If that does not solve it for you, I suggest you raise a ticket in the main [Stylus project's issue tracker](https://github.com/stylus/stylus)

**Comment by huilang-me** [comment]
Not work in Windows :cry:

**Comment by Molunerfinn** [comment]
I also have this problem on mac when I saved a stylus file which has '@import "nib"' ....However, I can build the *.styl files corretly by using sublime build system with 'cmd+b' and there is no error... I have no idea with it..
