### ISSUE TITLE
Add autocomplete support for : ;

### ISSUE THREAD

**Issue by alanaasmaa** [billymoon/Stylus#80]
Hi, i love stylus but i still like to use : ; to make my code look more clean. 

Autocompletion does not include the, Is it possible to get a setting to include them ?

**Comment by grassator** [comment]
@alanaasmaa which autocompletion are you using? Stylus package [doesn't include any by default](https://github.com/billymoon/Stylus#notice-to-existing-users).

**Comment by alanaasmaa** [comment]
`	"installed_packages":
	[
		"A File Icon",
		"AdvancedNewFile",
		"All Autocomplete",
		"Color Highlighter",
		"DocBlockr",
		"Emmet",
		"Git",
		"GitGutter",
		"Gulp",
		"HTML-CSS-JS Prettify",
		"HTML5",
		"jQuery",
		"Laravel Blade Highlighter",
		"LESS",
		"Material Theme",
		"Package Control",
		"PHP Codebeautifier",
		"PHP Companion",
		"ProjectManager",
		"SideBarEnhancements",
		"Smarty",
		"Stylus",
		"Stylus Clean Completions",
		"SublimeCodeIntel",
		"SublimeLinter",
		"SublimeLinter-contrib-htmlhint",
		"SublimeLinter-csslint",
		"SublimeLinter-jshint",
		"SublimeLinter-php",
		"SublimeLinter-phpcs",
		"SublimeLinter-phpmd",
		"TabsExtra"
	]`

Theser are my packages. Oh i didnt know that,.

**Comment by grassator** [comment]
@alanaasmaa I think then you are using [Stylus Clean Completions](https://github.com/lnikell/stylus-clean-completions) for the autocomplete which explicitly doesn't support semicolons, so this is something you need bring up with the package author or fork it and include the (semi)colons.

If you are OK with Emmet expansions (like `d:n` + Tab -> `display: none;`), [you can configure emmet to include the (semi)colons](https://forum.sublimetext.com/t/add-to-stylus-emmet/15269).

Since either way this is not connected to the Stylus syntax package, I'm closing this issue.
